services:
  app:
    build:
      context: .
      target: prod
    container_name: acquisitions-app-prod
    env_file:
      - .env.production
    ports:
      - "${PORT:-3000}:3000"
    restart: unless-stopped
    command: npm run start
